hmcts/div-decree-absolute-frontend

Jenkinsfile_CNP
infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/output.tf
infrastructure/preview.tfvars
infrastructure/prod.tfvars
infrastructure/saat.tfvars
infrastructure/sandbox.tfvars
infrastructure/sprod.tfvars
infrastructure/state.tf
infrastructure/variables.tf

Thisiis the initial project setup for Jenkins and Terraform. Copied from DN and 
- [/] New feature (non-breaking change which adds functionality)
NA
* Hardware:
* JDK:
- [/ ] My code follows the style guidelines of this project

copy and update Jenkins and .tf files from DN

---

config/default.yml
steps/done/Done.content.json
steps/done/Done.html
steps/done/Done.step.js
steps/petitioner/exit-no-longer-wants-to-proceed/ExitNoLongerWantsToProceed.content.json
steps/petitioner/exit-no-longer-wants-to-proceed/ExitNoLongerWantsToProceed.html
steps/petitioner/exit-no-longer-wants-to-proceed/ExitNoLongerWantsToProceed.step.js
test/unit/steps/petitioner/done.test.js
test/unit/steps/petitioner/exitNoLongerWantsToProceed.test.js
test/unit/views/filters/a11y.test.js
test/unit/views/filters/address.test.js
test/unit/views/filters/date.test.js
test/unit/views/filters/hyphenate.test.js
test/unit/views/filters/index.test.js
test/unit/views/filters/upper.test.js
views/filters/a11y.js
views/filters/hyphenate.js
yarn.lock

Created 2 new pages 
- Done page for when user selects yes to "Do you want to finalise your divorce?"
- Exit page when user selects no to "Do you want to finalise your divorce?"
Also added tests for views/filters

Created preliminary Done and Exit page for DA

---

config/default.yml
mocks/services/case-orchestration/retrieve-case/mock-case.json
steps/petitioner/progress-bar/ProgressBar.content.json
steps/petitioner/progress-bar/ProgressBar.html
steps/petitioner/progress-bar/ProgressBar.step.js
test/unit/steps/petitioner/progressBar.test.js

+ Add files to case mock
+ Add files to default.yml
+ Update progressbar html to show docuement list
+ Create test to test downloadFiles function
* Hardware:
* JDK:

DIV 5041: Add DA Download documents to frontend

---

config/default.yml
mocks/steps/modify-session/sections/caseState.html
steps/petitioner/progress-bar/ProgressBar.content.json
steps/petitioner/progress-bar/ProgressBar.html
steps/petitioner/progress-bar/ProgressBar.step.js
test/unit/steps/petitioner/progressBar.test.js

DIV-5073: DA holding Page

---

charts/div-da/values.preview.template.yaml

Current Helm Chart Config is pointing to Preview For Test Purposes.
* Hardware:
* JDK:

Point Preview to Master Branch

---

config/default.yml
mocks/services/case-orchestration/retrieve-case/mock-case.json
steps/petitioner/progress-bar/ProgressBar.content.json
steps/petitioner/progress-bar/ProgressBar.html
steps/petitioner/progress-bar/ProgressBar.step.js
steps/petitioner/progress-bar/sections/DivorceAwaiting.html
steps/petitioner/progress-bar/sections/DivorceGranted.html
steps/petitioner/progress-bar/sections/DivorceRequested.html
test/unit/services/googleAnalytics.test.js
test/unit/steps/petitioner/progressBar.test.js

Updates the progress bar page to show divorce granted content: decree absolute file, content saying you're divorced etc

DIV-5273: Final DA Landing Page

---

views/includes/propositional_navigation.html

Remove check from sign out button so the sign out link will show, this follows the same behaviour as the other frontends.
* Hardware:
* JDK:

DIV-5183: Sign out link in the header

---

infrastructure/variables.tf

Update download document endpoint
Fixes # (DIV-5324)

DIV-5324: Update download endpoint variable

---

test/unit/steps/petitioner/applyForDecreeAbsolute.test.js

Reverting unintentional unit test change

---

steps/petitioner/apply-for-da/ApplyForDecreeAbsolute.content.json

Text change on continue with divorce page.
Story: https://tools.hmcts.net/jira/browse/DIV-5314
Existing tests did not require any change.

DIV-5314: Text change on continue with divorce page

---

steps/petitioner/progress-bar/ProgressBar.content.json
test/unit/steps/petitioner/progressBar.test.js

Text change on holding page
Story: https://tools.hmcts.net/jira/browse/DIV-5315
Existing test modified

DIV-5315: Text change on holding page

---

mocks/services/case-orchestration/retrieve-case/mock-case.json
steps/petitioner/progress-bar/ProgressBar.content.json
test/unit/steps/petitioner/progressBar.test.js

This can only be merged after this PR is merged and deployed to prod: https://github.com/hmcts/div-case-orchestration-service/pull/379
Unit tests and manual test.

DIV-5312: Displaying DA-related dates on landing page

---

Jenkinsfile_CNP

[DIV-5129](https://tools.hmcts.net/jira/browse/DIV-5129)
Pipeline change
* Hardware:
* JDK:

Reintroduce Yarn Audit

---

steps/petitioner/exit-no-longer-wants-to-proceed/ExitNoLongerWantsToProceed.content.json
test/unit/steps/petitioner/exitNoLongerWantsToProceed.test.js

+ Update case-mock.json to have these new dates
* Hardware:
* JDK:

DIV-5170: Update sign out page to have dynamic dates

---

config/default.yml
mocks/services/case-orchestration/retrieve-case/mock-case.json
steps/petitioner/progress-bar/ProgressBar.content.json
test/unit/steps/petitioner/progressBar.test.js

Add decree nisi answers to da landing page
Fixes # (DIV-5198)

DIV-5198: Add decree nisi answers to landing page

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
charts/div-da/Chart.yaml
charts/div-da/requirements.yaml
charts/div-da/values.preview.template.yaml

Upgraded Helm chart requirements to use hmctspublic

---

steps/cookies-policy/CookiesPolicy.html

Fix `"<th>" tags should have "id" or "scope" attributes` issue by sonar

---

infrastructure/main.tf

- [Y] Bug fix (non-breaking change which fixes an issue)
* Hardware:
* JDK:
- [y] My code follows the style guidelines of this project
- [y] I have performed a self-review of my own code
- [y] I have commented my code, particularly in hard-to-understand areas
- [y] I have made corresponding changes to the documentation
- [y] My changes generate no …

Use hmcts/cnp-module-redis

---

infrastructure/main.tf

Update cnp-module-webapp reference

---

package.json
yarn.lock

To resolve special characters stored in CCD in HTML encoded state.
[DIV-5552](https://tools.hmcts.net/jira/browse/DIV-5552)
* Hardware:
* JDK:

DIV-5552 Update to OPP 5.3.0

---

infrastructure/prod.tfvars

[DIV-5756 Enable webchat on live environment](https://tools.hmcts.net/jira/browse/DIV-5756)
- Add live webchat environment variables

Webchats - add live environment variables

---

infrastructure/variables.tf

To test webchats config is working correctly temporarily turn webchats feature on.

enable webchat (test for prod)

---

infrastructure/variables.tf

Reverts hmcts/div-decree-absolute-frontend#81
The webchats test is now complete. This PR will disable it again

Revert "enable webchat (test for prod)"

---

Jenkinsfile_CNP
helpers/setupSecretsHelper.js

PFE has it's redis url as host, copied it over and didn't check 🤦‍♂
Missed chart publishing in this repo

Enable chart publishing and fix typo

---

app.js
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/DIV-5608
- Removed unused infra variables
- Swapped Smart Survey URL to new correct one
Type of change

DIV-5608: Updated Smart Survey URL

---

Dockerfile
charts/div-da/Chart.yaml
charts/div-da/values.aat.template.yaml
charts/div-da/values.preview.template.yaml
charts/div-da/values.yaml

Lots of config is missing on the AAT AKS deployment, formatting is weird here, this might fix it

Try fix AAT build by reformatting yaml

---

common/content.json
mocks/services/case-orchestration/retrieve-aos-case/mock-case-resp.json
mocks/services/case-orchestration/retrieve-case/mock-case.json
mocks/services/case-orchestration/submit-da/__/mock-case.json
steps/accessibility-statement/AccessibilityStatement.content.json
steps/contact-divorce-team-error/ContactDivorceTeamError.content.json
steps/exit/Exit.content.json
steps/petitioner/progress-bar/PetitionerProgressBar.content.json
steps/respondent/progress-bar/RespondentProgressBar.content.json
test/unit/resources/courtsList.json
views/errors/error-content.json

https://tools.hmcts.net/jira/browse/RPET-32

Updating ctsc opening hours

---

.github/CONTRIBUTING.md
assets/js/showHideContent.js
common/steps/progress-bar/ProgressBar.step.js
mocks/services/case-orchestration/retrieve-aos-case/mock-case-resp.json
mocks/services/case-orchestration/retrieve-case/mock-case.json
mocks/services/case-orchestration/submit-da/__/mock-case.json
mocks/steps/modify-session/ModifySession.html
steps/respondent/progress-bar/RespondentProgressBar.step.js
yarn.lock

Just minor code cleanups like adding missing semi-colons, getting rid of redundant things etc

Code cleanup

---

charts/div-da/values.preview.template.yaml
infrastructure/variables.tf

client_id variable removed

---

charts/div-da/Chart.yaml
charts/div-da/requirements.yaml
charts/div-da/values.demo.template.yaml
charts/div-da/values.preview.template.yaml
infrastructure/demo.tfvars
infrastructure/variables.tf
test/w3cjs/index.js

Rebased off master to fix Demo's failing pipeline. 
Moved to Bitnami charts Repository and upgraded redis to version 10.0.0
Tests pass locally. 
Pipeline green.

Rebase off master to fix failing pipeline

---

charts/div-da/Chart.yaml
charts/div-da/requirements.yaml
steps/entry/Entry.step.js

https://tools.hmcts.net/jira/browse/RPET-73
Modified condition to avoid incorrect mismatch. 
Moved to Bitnami charts repository and upgraded redis to version 10.0.0 to fix failing pipeline. 
Tests pass locally. 
Manual testing recorded in the PR environment.

RPET-73: Modify condition to avoid incorrect mismatch

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/RPET-242

Remove deprecated method installCharts

---

server.js
services/setupSecrets.js

https://tools.hmcts.net/jira/browse/RPET-298

RPET-298-app-insights-config

---

app.js
config/default.yml
package.json
views/includes/phase_banner.html
yarn.lock

https://tools.hmcts.net/jira/browse/WLA-590

WLA-590: Enable Language Toggle on UI

---

package.json
yarn.lock

bump dependency version and add to resolutions

---

package.json
yarn.lock

Address CVE issues.
[RPET-361](https://tools.hmcts.net/jira/browse/RPET-361)
* Hardware:
* JDK:

RPET-361: fix CVE issues

---

package.json

Made changes in Package.json to fix Pa11y report.
* Hardware:
* JDK:

Pa11y report fix

---

config/default.yml
mocks/services/case-orchestration/retrieve-aos-case/mock-case-resp.json
mocks/services/case-orchestration/retrieve-case/mock-case.json
steps/petitioner/progress-bar/PetitionerProgressBar.content.json
steps/respondent/progress-bar/RespondentProgressBar.content.json
test/unit/steps/petitioner/progressBar.test.js
test/unit/steps/respondent/progressBar.test.js

Display General orders on DA Frontend
Fixes https://tools.hmcts.net/jira/browse/DIV-6516
* Hardware:
* JDK:

DIV-6516: Display General order documents

---

security.sh

Adding a script to execute OWASP zaproxy task in the nightly build pipeline.
Ticket:
https://tools.hmcts.net/jira/browse/RPET-657

RPET-657: Added ./security.sh script

---

security.sh

https://tools.hmcts.net/jira/browse/RPET-657

RPET-657: nightly build report

---

package.json
yarn.lock

Bump up redis version
Fixes https://tools.hmcts.net/jira/browse/RPET-981

PET-981: Fix dependency checks

---

charts/div-da/values.yaml
package.json
test/functional/helpers/idamHelper.js
test/resources/basic-divorce-session.json
yarn.lock

Fix functional test: 403 error access denied on CCD
Fixes https://tools.hmcts.net/jira/browse/RPET-981

RPET-981: Fix dependency errors

---

test/functional/helpers/idamHelper.js

Removing "testGroupCode". No longer needed.
Fixes https://tools.hmcts.net/jira/browse/RPET-981

RPET-981: Removing test group code. No longer needed

---

test/functional/paths/petitionerPages.js
test/functional/paths/respondentPages.js

Disussed with Ruban, Vivek, Arun and Rob.

It was discussed with TA team that we don't need to run e2e tests for  static pages

---

package.json
yarn.lock

Upgrading div-idam-test-harness as an attempt to fix the build/
Fixes https://tools.hmcts.net/jira/browse/RPET-1014

RPET-1014: Upgrading idam test harness

---

app.js
charts/div-da/values.preview.template.yaml
config/custom-environment-variables.yml
config/default.yml
package.json
steps/avaya-webchat/AvayaWebchat.html
test/unit/views/contactus.test.js
views/includes/head.html
views/includes/problem_with_this_page.html
yarn.lock

New Antenna API call and remove redundant 8x8 code
[DFR-119](https://tools.hmcts.net/jira/browse/DFR-119)
- [ x] New feature (non-breaking change which adds functionality)

DFR-119:  New Antenna API and remove 8x8 code

---

README.md
server.js

Output Redis url and encryptionAtRestKey to log for Damon
* Hardware:
* JDK:

Output Redis Info to Log

---

README.md
server.js

Reverts hmcts/div-decree-absolute-frontend#189

Revert "Output Redis Info to Log"

---

charts/div-da/Chart.yaml
charts/div-da/values.preview.template.yaml
config/custom-environment-variables.yml
config/default.yml
package.json
services/redis.js
sonar-project.properties
yarn.lock

DFR-701: Upgrade One Per Page library

---

assets/js/cookiesManager.js

Test for presence of cookie elems before calling onClick()

DFR-37-Webchat-Fix

---

assets/js/cookiesManager.js

Update cookie domain for prod
Do Not Merge Until AAT Dynatrace Testing Is Complete

dfr-37-prod-cookie-domain

---

infrastructure/main.tf

Updating app key

---

charts/div-da/Chart.yaml
charts/div-da/values.yaml

https://tools.hmcts.net/jira/browse/DTSSE-1395

Increase CPU request

---

Jenkinsfile_CNP
README.md

https://tools.hmcts.net/jira/browse/DFR-1086

DFR-1086 Remove pipeline trigger

---

Jenkinsfile_CNP
README.md
charts/div-da/Chart.yaml

Reconfigure the jenkins file inline with changes made to the pipeline in DTSPO-9025 (which moves label checks and additional test execution logic into the pipeline itself).

Reconfig for dtspo 9025

---

services/fileManagement.js

suppress content length limit for file upload

---

services/fileManagement.js
sonar-project.properties

sonarqube suppression

---

yarn.lock

Fix dependency issues

---

charts/div-da/Chart.yaml
charts/div-da/values.yaml

https://tools.hmcts.net/jira/browse/DTSSE-3240
to fix aat OOM killed

Update mem Chart.yaml

---

test/java/build.gradle

DFR-3783 Remove Jitpack dependency
* Hardware:
* JDK:

DFR-3783 Remove Jitpack dependency
